name: hybrid_search_cuda11 #for outdated cuda
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - setuptools
  - cudatoolkit=11.6
  - pytorch<=1.13
  - sentence-transformers
  - jupyter
  - pip:
      - langchain>=0.1.9
      - langchain_community>=0.0.22
      - opensearch-py>=2.4.2
      - twine
      - adapters
      - pycomfort>=0.0.15
      - psutil #some weird dependency
      - pyvespa
      - transformers>=4.35.2
      - FlagEmbedding