name: hybrid_search
channels:
  - conda-forge
  - bioconda
  - pytorch
  - plotly
  - defaults
dependencies:
  - python=3.10
  - setuptools
  - pytorch
  - pdfminer.six
  - pydantic
  - sentence-transformers
  - pip:
      - langchain>=0.0.352
      - langchain-community>=0.0.9
      - opensearch-py
      - twine
      - adapters
      - pycomfort>=0.0.15
      - psutil #some weird dependency