name: hybrid_search
channels:
  - conda-forge
  - bioconda
  - pytorch
  - plotly
  - defaults
dependencies:
  - python=3.10
  - setuptools
  - pytorch
  - pdfminer.six
  - pip:
      - langchain
      - pycomfort>=0.0.13
      - sentence_transformers
      - opensearch-py
      - twine