name: hybrid_search
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - setuptools
  - pydantic
  - pytorch
  - sentence-transformers
  - jupyter
  - pip:
      - langchain>=0.1.12
      - langchain_community>=0.0.28
      - opensearch-py>=2.4.2
      - twine
      - adapters
      - pycomfort>=0.0.15
      - psutil #some weird dependency
      - pyvespa
      - transformers>=4.35.2
      - FlagEmbedding