name: hybrid_search
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - setuptools
  - pydantic
  - pytorch
  - sentence-transformers
  - jupyter
  - pip:
      - langchain>=0.2.11
      - langchain_community>=0.2.10
      - opensearch-py>=2.6.0
      - twine
      - adapters
      - pycomfort>=0.0.15
      - psutil #some weird dependency
      - transformers>=4.35.2
      - FlagEmbedding>=1.2.10