name: hybrid_search
channels:
  - conda-forge
  - bioconda
  - pytorch
  - plotly
  - defaults
dependencies:
  - python=3.10
  - setuptools
  - pytorch
  - pdfminer.six
  - pydantic
  - pip:
      - langchain>=0.0.352
      - pycomfort>=0.0.13
      - sentence_transformers
      - opensearch-py
      - twine
      - adapters
      - pycomfort>=0.0.15
      - psutil #some weird dependency